# Generated by Django 4.2.7 on 2023-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainsentimentdata",
            name="clean",
            field=models.CharField(default="NaN", max_length=2000),
        ),
        migrations.AlterField(
            model_name="trainsentimentdata",
            name="unclean",
            field=models.CharField(default="NaN", max_length=2000),
        ),
        migrations.AlterField(
            model_name="validsentimentdata",
            name="clean",
            field=models.CharField(default="NaN", max_length=2000),
        ),
        migrations.AlterField(
            model_name="validsentimentdata",
            name="unclean",
            field=models.CharField(default="NaN", max_length=2000),
        ),
    ]
