# Generated by Django 4.2.7 on 2023-12-21 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_alter_trainsentimentdata_clean_and_more"),
        ("server", "0002_remove_company_company_id_remove_company_id_and_more"),
    ]

    operations = []
