# Generated by Django 4.2.7 on 2023-12-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "server",
            "0004_company_trainable_alter_trainsentimentdata_sentiment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="trainable",
            field=models.BooleanField(default=True),
        ),
    ]
