# Generated by Django 4.2.7 on 2023-12-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_alter_company_trainable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="trainable",
            field=models.BooleanField(default=False),
        ),
    ]
