# Generated by Django 4.2.7 on 2023-12-22 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0004_prediction_avg_sentiment_prediction_stock_val_and_more"),
        ("server", "0006_alter_company_trainable"),
    ]

    operations = []
