# Generated by Django 4.2.7 on 2023-12-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0008_traintrenddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_info",
            field=models.CharField(default="NaN", max_length=300),
        ),
        migrations.AddField(
            model_name="company",
            name="company_logo",
            field=models.CharField(default="NaN", max_length=300),
        ),
    ]
